Add workflow to enforce versioning labels
bigbinary/neeto-ui pull request #1048
Opened 2022-04-05 16:31 UTC by shamilsdq

Closes #1047 

- Added workflow to ensure exactly one of 'major', 'minor' or 'patch' label is set
- Added release and non-release types for major, minor and patch

2022-04-06 09:28 UTC, shamilsdq commented
@amaldinesh7

2022-04-07 06:26 UTC, shamilsdq commented
Tagging option has been set according to the presence of release label

@amaldinesh7

2022-04-07 09:57 UTC, amaldinesh7 requested changes
@shamilsdq _a Please check the comment

2022-04-07 10:07 UTC, shamilsdq commented on .github/workflows/version-bumper.yml
> +    steps:
Done

2022-04-07 10:08 UTC, shamilsdq commented
Replaced old version bumping steps with new version bumping steps in publish.yml

2022-04-07 12:07 UTC, amaldinesh7 approved these changes

2022-04-07 12:07 UTC, merged