Implemented setting the pagination and sorting config in URL query parameters
bigbinary/neeto-ui pull request #1768
Opened 2023-08-01 15:24 UTC by Calvinwilson99

- Fixes #1767 

**Description**
Added: **BREAKING** Mechanism to set the pagination and sorting config in URL query parameters.

**Checklist**

- [ ] I have made corresponding changes to the documentation.
- ~~[ ] I have updated the types definition of modified exports.~~
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

2023-08-01 17:17 UTC, Calvinwilson99 commented
@ajmaln _a. Please review.

Any `neetoUI` table in products and nanos that are not overriding the `onChange` prop will be affected by this change. We need to look into handling it during release.
If the `onChange` prop is being overriden the changes in this PR will not be functional, so we can change them after release.

2023-08-11 15:42 UTC, ajmaln reviewed
@Calvinwilson99 _a As discussed, let's add a boolean prop to enable/disable the behaviour

2023-08-14 09:17 UTC, Calvinwilson99 commented
@ajmaln _a. Added prop to disable setting query parameters in URL.

2023-08-14 12:07 UTC, ajmaln approved these changes
@Calvinwilson99 _a Please check the minor suggestions. Please assign to @amaldinesh7 for further review

2023-08-14 12:07 UTC, ajmaln commented on stories/Components/TableStoriesDocs/TableSortingDocs.mdx
> +  noop if no functionality is needed.
Mention about `shouldEnableSortingConfig`

2023-08-14 12:07 UTC, ajmaln commented on src/components/Table/index.jsx
> +  shouldSetTableConfig = false,
```suggestion
  preserveTableStateInQuery = false,
```

2023-08-14 14:33 UTC, Calvinwilson99 commented
@amaldinesh7 _a. Please review.

2023-08-16 10:12 UTC, amaldinesh7 requested changes
@Calvinwilson99 _a Minor suggestion. Rest LGTM.

2023-08-16 17:59 UTC, Calvinwilson99 commented on src/components/Table/constants.js
> +export const TABLE_SORT_ORDERS = { asc: "ascend", desc: "descend" };
@amaldinesh7 _a.
The table requires `ascend` and `descend` to work. The query parameters will be used by products to send queries to the backend. So, if we directly set `ascend` and `descend` in the URL without converting them, we would have to convert them to `asc` and `desc` in every product.
I think the better option would be to use the converted forms in the URL and products can use them as is.

2023-08-17 16:55 UTC, amaldinesh7 approved these changes

2023-08-17 16:55 UTC, merged