Handled dot paths in ScrollToErrorField component
bigbinary/neeto-ui pull request #1775
Opened 2023-08-02 12:08 UTC by Calvinwilson99

- Fixes #1741 

**Description**
Handled dot paths in ScrollToErrorField component

**Checklist**

- ~~[ ] I have made corresponding changes to the documentation.~~
- ~~[ ] I have updated the types definition of modified exports.~~
- [x] I have verified the functionality in some of the neeto web-apps.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary label (patch/minor/major - If package publish
      is required).

2023-08-02 12:13 UTC, Calvinwilson99 commented
@ajmaln _a. Please review.

2023-08-02 14:30 UTC, ajmaln reviewed
@Calvinwilson99 _a Let's add a story as discussed

2023-08-02 16:07 UTC, Calvinwilson99 commented
@ajmaln _a. Added a story showing scrolling in action.

2023-08-03 15:58 UTC, ajmaln approved these changes
@amaldinesh7 _a Please review

2023-08-03 17:41 UTC, amaldinesh7 approved these changes

2023-08-03 17:44 UTC, amaldinesh7 requested changes
@Calvinwilson99 _a Please check the comment.

Update the description as per the format.

2023-08-03 17:44 UTC, amaldinesh7 commented on src/components/formik/Form/index.jsx
> +    { className, children, formikProps, formProps, scrollToErrorField = true },
We can keep the default value as false itself.

2023-08-04 06:58 UTC, Calvinwilson99 commented
@amaldinesh7 _a. Made the requested changes.

2023-08-04 13:07 UTC, merged