Sync avatar
bigbinary/neeto-ui pull request #62
Opened 2020-12-01 08:11 UTC by yedhink

Fixes #31 

Changes/Enhancements:
- Didn't copy paste NitroUI component as is, because I felt neeto-ui has done stuff better, like rendering default avatar etc
- Fixed issue with Indicator not being displayed over avatar when using default avatar. The following was the issue:
![avatar-component-indicator-top-right-corner-render-default](https://user-images.githubusercontent.com/31244999/100713736-c4a58100-33da-11eb-9660-6cbd3f35c151.png)
- Handled cases where no contact info is provided/contact name is empty
- Handled case where activity attr is invalid
- Removed unnecessary conditions like `userInitial ? `

@edwinbbu _a
Please review the PR and merge if everything looks good. Thanks

2020-12-01 20:51 UTC, goutham-subramanyam commented
@yedhink _a

1. We need to include `Activity` in `renderUserImage` as well.
2. The `isOnline` prop is being updated to `status` ([Ref](https://github.com/bigbinary/neeto-help-web/pull/8592/files#diff-53ad57a285a90f0d78b1b57db2302fa4e41c22b830fa333906c88531bc8c749e)). We need to update that as well.

Also, please tag in me all the syncing PRs. Thanks.

2020-12-02 12:23 UTC, yedhink commented
@vinay0x _a

Please review the PR.

How exactly should we deal with conflicts here? The latest bundles are being in conflict. Manually fixing the conflicts in bundles is a task since the file content is too big to diff. Can we merge this overwrite the bundles in master?

cc: @goutham-subramanyam

2020-12-02 12:25 UTC, vinay0x commented
@yedhink _a Rebase with master and ignore the conflicts in bundles. You can accept the master version But make sure that the lib folder contents are latest in your branch. Then create a build and push it.

2020-12-02 15:15 UTC, yedhink commented
@vinay0x _a

Have rebased.

Let me know if this is good to be merged.

2020-12-02 20:18 UTC, goutham-subramanyam requested changes
@yedhink

2020-12-02 20:18 UTC, goutham-subramanyam commented on lib/components/Avatar.js
> +        {status && <Indicator />}
The `Indicator` needs to be updated like in that PR.

2020-12-03 06:52 UTC, yedhink commented
@goutham-subramanyam _a

I have made the changes. Please review and merge if everything looks good.

2020-12-03 20:14 UTC, goutham-subramanyam requested changes
@yedhink _a

2020-12-03 20:14 UTC, goutham-subramanyam commented on lib/components/Avatar.js
> +        <Indicator status={status} />
We should have the `status` check. Else an unnecessary `<span>` will be rendered all the time right.

2020-12-03 20:14 UTC, goutham-subramanyam commented on lib/components/Avatar.js
> +        <svg className="object-cover w-full h-full p-2 overflow-hidden text-white bg-purple-400 rounded-full" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
If we have added remixicons, please replace with that. Else its fine.

2020-12-04 07:41 UTC, yedhink commented
@goutham-subramanyam _a

Please review and merge if everything looks good.

The status check is done within `Indicator` component.

2020-12-04 14:18 UTC, goutham-subramanyam approved these changes

2020-12-04 14:18 UTC, merged