Updated Documentation
bigbinary/neeto-ui pull request #695
Opened 2021-12-03 11:45 UTC by ajmaln

- Fixes #693 
  - Added `react-toastify` peer dependency documentation
<br>

- Fixes #686 
  - Added stories with different variants for Container and Scrollable
  - Added documentation on props for Container and Scrollable

@ajmaln _a

2021-12-03 12:25 UTC, ajmaln commented
@amaldinesh7 _a Please review.

cc: @karthiknmenon

2021-12-03 19:31 UTC, amaldinesh7 requested changes
@ajmaln _a Please take a look at the comments.

2021-12-03 19:31 UTC, amaldinesh7 commented on README.md
> +**NeetoUI** has few peer dependencies which are required to use NeeetoUI properly. Install those peer dependencies using the below command.:
Please fix the typo `NeeetoUI`. Please remove the full stop and keep the colon

2021-12-03 19:31 UTC, amaldinesh7 commented on stories/Introduction.stories.mdx
> +**NeetoUI** has few peer dependencies which are required to use NeeetoUI properly. Install the peer dependencies using the below command.:
Same here

2021-12-04 04:21 UTC, ajmaln commented
@amaldinesh7 _a fixed the typo.

2021-12-04 11:38 UTC, merged