Splited code of components in layouts
bigbinary/neeto-ui pull request #744
Opened 2022-01-06 10:59 UTC by AJIL-PAUL

Fixes #739 

Splitted codes in the following components under layouts:
```
- Sidebar
    |_ index.js
    |_ FeaturedTooltip.js
    |_ NavIconWrapper.js
    |_ NeetoLogo.js
    |_ ProfileSection.js
    |_ ProfileSectionTooltip.js
    |_ Footer
         |_ index.js
         |_ AppSwitcher.js
         |_ ChangeLog.js
    |_constant.js

- AppSwitcher
    |_ index.js
    |_ AppLink.js
    |_ Body.js

```

@amaldinesh7 _a Please review

2022-01-07 08:08 UTC, amaldinesh7 requested changes
@AJIL-PAUL _a Please check the comments

2022-01-07 08:08 UTC, amaldinesh7 commented on lib/components/layouts/Sidebar/index.js
> +Sidebar.propTypes = {
Can we move this proptypes object into constants?

2022-01-07 08:08 UTC, amaldinesh7 commented on lib/components/layouts/AppSwitcher/index.js
> +AppSwitcher.propTypes = {
Move to constants

2022-01-07 08:08 UTC, amaldinesh7 commented on lib/components/layouts/AppSwitcher/index.js
> +const sizes = { lg: "lg", sm: "sm" };
move to constants

2022-01-07 08:08 UTC, amaldinesh7 commented on lib/components/layouts/AppSwitcher/index.js
> +const envs = {
move to constants

2022-01-09 07:46 UTC, AJIL-PAUL commented
@amaldinesh7 _a Updated based on comments. Please review

2022-01-10 01:44 UTC, merged