Removed collapse icon from Sidebar
bigbinary/neeto-ui pull request #792
Opened 2022-01-25 09:31 UTC by ajmaln

- Fixes #788 
- Removed `collapsible` prop
- Removed `onCollapse` prop
- Made Sidebar expanded if Sub Nav items are provided
- Added stories with sub items and without sub items

2022-01-25 15:33 UTC, amaldinesh7 requested changes

2022-01-26 14:16 UTC, karthiknmenon commented on lib/components/layouts/Sidebar/index.js
> +  const hasNoSubItems = all((link) => either(isNil, isEmpty)(link.items))(
The provision for subItems can be removed. Once this PR is merged, we will put up a message in neeto about the change. 
As per the new design system, we would not be having any nav subLinks in the sidebar. 

@ajmaln @amaldinesh7

2022-01-27 05:11 UTC, ajmaln commented
@amaldinesh7 I have removed the sub-items from Sidebar, please take a look.

2022-01-27 05:40 UTC, amaldinesh7 approved these changes

2022-01-27 05:40 UTC, merged