Added help text to EmailInput component
bigbinary/neeto-ui pull request #846
Opened 2022-02-15 09:19 UTC by Thejus-Paul

Fixes #845 
- Added help text to EmailInput component and its story.
- Added default props for `error` and `label`.
- Rearranged the `index.js` file in alphabetic order.
- Added feature to prune similar values.
- Added a custom yup validation test.

2022-02-15 09:41 UTC, Thejus-Paul commented
![help_text_email_component](https://user-images.githubusercontent.com/32426070/154035162-2191c931-7590-40af-9378-0af3782dfb92.gif)

@karthiknmenon _a Please review.

2022-02-15 12:28 UTC, Thejus-Paul commented
![prune_duplicate_values](https://user-images.githubusercontent.com/32426070/154061923-b91a57f3-71c1-4c82-be46-e4e5d1dd9508.gif)
`react-select`'s multi-select text input field has some issues while removing duplicate values. The delete operation will not work as shown above. Since EmailInput component was built using this, it has inherited this issue. Thus, I have added a simple fix to prune the duplicate values.

2022-02-17 10:24 UTC, karthiknmenon commented
@ajmaln _a Please review.

2022-02-17 16:49 UTC, amaldinesh7 requested changes
@Thejus-Paul _a Please check the comments.

2022-02-17 16:49 UTC, amaldinesh7 commented on lib/components/EmailInput.js
> +  error: PropTypes.oneOfType([String, Array]),
Let's keep only the string type for the error prop. Please make the changes as discussed over the call. Let me know if there is any difficulty with that.

2022-02-18 06:15 UTC, Thejus-Paul commented
@amaldinesh7 _a Please review.

2022-02-18 08:21 UTC, amaldinesh7 approved these changes

2022-02-18 08:22 UTC, merged