Added an email counter
bigbinary/neeto-ui pull request #872
Opened 2022-02-21 13:16 UTC by Thejus-Paul

Fixes #870 
- Added an email counter and used it on Formik story.

2022-02-21 13:36 UTC, Thejus-Paul commented
![email_counter](https://user-images.githubusercontent.com/32426070/154965410-7554e8f5-180d-4b28-882a-88bfe67976bc.gif)

@amaldinesh7 _a Please review.

2022-02-21 15:22 UTC, subins2000 commented
@Thejus-Paul Hi Thejus, just a suggestion: Notice how the input field's height changes when emails are added. I think it's better if the height of input field remains the same whether or not there are any items in it. I came across this in neetoChat where in a form the email input is bigger than every other field in the form.

2022-02-22 07:53 UTC, Thejus-Paul commented
@subins2000 I also found that to be an issue. Please check the image below. After increasing the size of the email input field, it didn't feel good to me. This is after making the select component below it to size "large". 
![image](https://user-images.githubusercontent.com/32426070/155084201-0fbda29e-0a05-420c-85ea-77f06f8b5d9a.png)
The image below is how it is rendering currently and this one felt better to me.
![image](https://user-images.githubusercontent.com/32426070/155084873-71d15855-3749-4751-9d73-b57427fd7dd5.png)
When the user types, maybe because of the motion or because of the content inside it, I didn't feel the increase in the input field that much awkward to me.
![image](https://user-images.githubusercontent.com/32426070/155085133-11adcd35-397d-4f28-8673-f7040549fb2d.png)
What is your thought on this @amaldinesh7 ?

2022-02-22 10:29 UTC, amaldinesh7 requested changes
@Thejus-Paul _a Please check the comment

2022-02-22 10:29 UTC, amaldinesh7 commented on lib/constants/EmailInput.js
> +export const getEmailsCount = values => renderValidEmails(values).length;
These ain't constants. Please move all the function to helpers/utils

2022-02-22 10:33 UTC, amaldinesh7 commented
> @subins2000 I also found that to be an issue. Please check the image below. After increasing the size of the email input field, it didn't feel good to me. This was after making the select component below it to a size large. ![image](https://user-images.githubusercontent.com/32426070/155084201-0fbda29e-0a05-420c-85ea-77f06f8b5d9a.png) The image below shows how it is rendering currently. This one felt better to me. ![image](https://user-images.githubusercontent.com/32426070/155084873-71d15855-3749-4751-9d73-b57427fd7dd5.png) When the user types, maybe because of the motion or the content inside it, I didn't feel the increase in the input field that much awkward to me. ![image](https://user-images.githubusercontent.com/32426070/155085133-11adcd35-397d-4f28-8673-f7040549fb2d.png) What is your thought on this @amaldinesh7 ?

Let's not make this change. Increased height in the default state looks weird. You can adjust the height of the container in which you use this component, such that it won't make a jerk to the UI. 

cc: @praveen-murali-ind

2022-02-22 10:52 UTC, Thejus-Paul commented
@amaldinesh7 _a Please review.

2022-02-22 11:05 UTC, Thejus-Paul commented
@amaldinesh7 _a Please review.

2022-02-22 11:20 UTC, amaldinesh7 approved these changes

2022-02-22 11:20 UTC, merged