Added tests for Alert component
bigbinary/neeto-ui pull request #921
Opened 2022-03-08 14:44 UTC by ajmaln

- Fixes #920 
- Added `loading` story for Alert

@ajmaln _a

2022-03-09 15:52 UTC, ajmaln commented
@amaldinesh7 _a Please review.

2022-03-09 19:52 UTC, amaldinesh7 approved these changes

2022-03-09 21:05 UTC, amaldinesh7 requested changes

2022-03-09 21:05 UTC, amaldinesh7 commented on stories/Overlays/Alert.stories.jsx
> +export const AlertLoading = () => {
We don't have to add this story, since we are going to remove the loading prop from alert and modal. Please revert the changes related to this story.

2022-03-09 21:06 UTC, amaldinesh7 commented
@ajmaln _a Please check the comment.

2022-03-10 06:31 UTC, ajmaln commented
@amaldinesh7 _a I have removed the loading story and test. Please review.

2022-03-10 08:04 UTC, amaldinesh7 approved these changes

2022-03-10 08:05 UTC, merged