Added tests for Label
bigbinary/neeto-ui pull request #965
Opened 2022-03-11 11:49 UTC by vysakh-m

Fixes #945

2022-03-11 12:00 UTC, vysakh-m commented
@amaldinesh7 _a Please review

2022-03-12 15:57 UTC, amaldinesh7 commented on tests/Label.test.js
> +        <p>Content</p>
we don't need to have a `p` tag inside render

2022-03-12 16:02 UTC, amaldinesh7 requested changes
@vysakh-m _a Please check the comment and assign to @ajmaln once fixed.

2022-03-14 08:21 UTC, vysakh-m commented
Resolved suggestion. @ajmaln _a Please review.

2022-03-14 14:36 UTC, ajmaln reviewed
@vysakh-m _a Please check the suggestion

2022-03-14 15:51 UTC, vysakh-m commented
@ajmaln _a Resolved suggestion. Please review

2022-03-14 20:25 UTC, ajmaln commented on lib/components/Label.js
> +            <HelpIcon data-testid="icon" size={16} {...otherHelpIconProps} />
let's pass the `data-testid` in `helpIconProps`

2022-03-14 21:41 UTC, ajmaln approved these changes

2022-03-14 21:43 UTC, merged